# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llBGBvarRcpp <- function(sigm, paraOrth) {
    .Call('move_llBGBvarRcpp', PACKAGE = 'move', sigm, paraOrth)
}

